apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1 
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap
      # env: 
      #   - name: MYSQL_ROOT_PASSWORD
      #     valueFrom: 
      #       configMapKeyRef:
      #         name: "db-configmap"
      #         key: "MYSQL_ROOT_PASSWORD"
      #   - name: MYSQL_DATABASE
      #     valueFrom: 
      #       configMapKeyRef:
      #         name: "db-configmap"
      #         key: "MYSQL_DATABASE"
      #   - name: MYSQL_USER
      #     valueFrom: 
      #       configMapKeyRef:
      #         name: "db-configmap"
      #         key: "MYSQL_USER"
      #   - name: MYSQL_PASSWORD
      #     valueFrom: 
      #       configMapKeyRef:
      #         name: "db-configmap"
      #         key: "MYSQL_PASSWORD"