apiVersion: v1
kind: Service
metadata: 
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: pod-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000